### ISSUE TITLE
Lock of ARN-Scripts "rfinfo" query

### ISSUE THREAD

**Issue by qigezhao** [6wilink/ARN-Scripts#3]
Sometimes, there will be two "rfinfo" update calls running. 
It's not urgent.
* GWS5K platform may not answer your request in a while when too much "rfinfo" called.

**Comment by qigezhao** [comment]
URGENT! Multi-calling "arn -m" will do multi "gws5001app rfinfo" at the same time.

**Comment by zhaoqige** [comment]
Add a query file lock. Works for now.
